import BackgroundService from "react-native-background-actions";
import { logger } from "../network/logger";
import { notificationService } from "./notificationService";

/**
 * Monochrome icon generated by expo-notifications from the app icon.
 * Android renders notification icons as silhouettes, so a proper drawable is
 * required — a mipmap launcher icon shows up as a white blob.
 */
const NOTIFICATION_ICON = { name: "notification_icon", type: "drawable" as const };
const NOTIFICATION_COLOR = "#E50914";

/**
 * Tapping the download notification should land on the Downloads tab so the
 * user can watch progress, not on Home. Expo Router maps this URI to `/downloads`.
 */
const NOTIFICATION_LINKING_URI = "finora://downloads";

let _active = false;
let _permissionRequested = false;

/**
 * Android 13+ requires the runtime POST_NOTIFICATIONS permission for the
 * foreground-service notification to be visible. Without it the notification is
 * silently dropped and the OS (especially MIUI) is far more likely to kill the
 * process — which is exactly what stops a background download.
 *
 * Asked once per app session, at the moment the user starts a download.
 */
async function ensureNotificationPermission(): Promise<void> {
  if (_permissionRequested) return;
  _permissionRequested = true;
  try {
    await notificationService.requestPermissions();
  } catch {
    // Non-fatal — the download still runs, only the notification may be hidden
  }
}

/**
 * Keeps the Android Foreground Service alive while FINORA has active downloads.
 * The actual network transfer runs inside expo-file-system — this task only
 * prevents Android from killing the process while the app is backgrounded.
 */
async function keepAliveTask(): Promise<void> {
  while (BackgroundService.isRunning()) {
    await new Promise((resolve) => setTimeout(resolve, 2000));
  }
}

/**
 * Starts the foreground service, or refreshes its notification when running.
 *
 * @param progressPercent 0-100, or undefined for an indeterminate bar.
 */
export async function startDownloadForeground(
  title: string,
  description: string,
  progressPercent?: number
): Promise<void> {
  const determinate = typeof progressPercent === "number";

  if (_active && BackgroundService.isRunning()) {
    try {
      await BackgroundService.updateNotification({
        taskTitle: title,
        taskDesc: description,
        linkingURI: NOTIFICATION_LINKING_URI,
        progressBar: determinate
          ? { max: 100, value: Math.round(progressPercent as number), indeterminate: false }
          : { max: 100, value: 0, indeterminate: true }
      });
    } catch {
      // Non-fatal
    }
    return;
  }

  try {
    await ensureNotificationPermission();

    await BackgroundService.start(keepAliveTask, {
      taskName: "finora_download",
      taskTitle: title,
      taskDesc: description,
      taskIcon: NOTIFICATION_ICON,
      color: NOTIFICATION_COLOR,
      linkingURI: NOTIFICATION_LINKING_URI,
      foregroundServiceType: ["dataSync"],
      progressBar: determinate
        ? { max: 100, value: Math.round(progressPercent as number), indeterminate: false }
        : { max: 100, value: 0, indeterminate: true }
    });
    _active = true;
    logger.info("[ForegroundService] Started");
  } catch (err: any) {
    // Non-fatal — downloads still work, just without process protection.
    logger.warn("[ForegroundService] Failed to start:", err?.message ?? err);
  }
}

/** Updates the notification of an already-running service. */
export async function updateDownloadNotification(
  title: string,
  description: string,
  progressPercent: number
): Promise<void> {
  if (!_active) return;
  try {
    await BackgroundService.updateNotification({
      taskTitle: title,
      taskDesc: description,
      progressBar: {
        max: 100,
        value: Math.round(progressPercent),
        indeterminate: false
      }
    });
  } catch {
    // Non-fatal
  }
}

/** Stops the foreground service. */
export async function stopDownloadForeground(): Promise<void> {
  if (!_active) return;
  try {
    await BackgroundService.stop();
    logger.info("[ForegroundService] Stopped");
  } catch {
    // Non-fatal
  } finally {
    _active = false;
  }
}

export function isForegroundActive(): boolean {
  return _active && BackgroundService.isRunning();
}
